logging:
  level:
    org.apache.ibatis: TRACE  # 显示参数类型绑定细节
    com.baomidou.mybatisplus: DEBUG
    java.sql.PreparedStatement: DEBUG  # 显示JDBC层类型

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.113.224.195:3306/ismp?useSSL=false&useServerPrepStmts=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: xieguangqiang

server:
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-not-delete-value: 0
      logic-delete-field: is_deleted
      logic-delete-value: 1



